<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/MMLib.Alvo/MMLib.Alvo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
