using MMLib.Alvo.Events;

using System.Data.Common;

namespace MMLib.Alvo.Data.EntityFrameworkCore.Internal;

/// <summary>
/// Alvo's own transactional outbox: its name, the DDL that creates it, the insert the write path adds to the
/// transaction that is already committing the row, and the three statements a dispatcher drains it with. A
/// framework bookkeeping table like the descriptor-versions and idempotency-record ones, not something the
/// descriptor-diff engine produces.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why <c>id</c> is the ordering key and there is no <c>sequence</c> column.</b> A UUIDv7 is time-ordered
/// in its high 48 bits and its stored text sorts lexicographically in time order on both shipped engines, so
/// the primary key <em>is</em> the queue order — with DDL identical on SQLite and PostgreSQL, honouring
/// <see cref="SystemSchemaInitializer"/>'s stated invariant. An <c>AUTOINCREMENT</c>/<c>IDENTITY</c> column
/// would break that invariant with no precedent in this repository, because each engine refuses the other's
/// spelling: SQLite refuses <c>… GENERATED BY DEFAULT AS IDENTITY</c> and PostgreSQL refuses
/// <c>AUTOINCREMENT</c>. Two consequences of the same measurement belong here, because neither is visible
/// from the DDL: the id is minted by <see cref="AlvoEventId.Create(DateTimeOffset)"/> and never by
/// <c>Guid.CreateVersion7()</c>, which sorts 49.9 % of its same-millisecond pairs backwards; and the column
/// is <c>TEXT</c> rather than a <c>BLOB</c>, because <see cref="Guid"/>'s default byte order is not
/// time-sortable at all. Measured in
/// <c>docs/superpowers/specs/evidence/2026-08-03-f3-pr5a-events/spike.txt</c>, Q1, Q2, Q6 and Q7 — Q7 is what
/// disqualifies <c>created_at</c> as the alternative: 10 000 successive clock reads produce 3 distinct values
/// at millisecond precision, and the audit stamp binds one instant per write, so ties there are structural.
/// </para>
/// <para>
/// <b>Why <c>SERIAL</c> is refused even though SQLite does not reject it.</b> SQLite <em>accepts</em>
/// <c>seq SERIAL</c>, parsing <c>SERIAL</c> as an unrecognised column type and silently giving a nullable
/// column that never increments (Q6). A "portable <c>SERIAL</c>" therefore passes every SQLite test in CI and
/// loses ordering in production, which is why <c>OutboxTableTests</c> asserts its absence rather than trusting
/// that nobody reaches for it.
/// </para>
/// <para>
/// <b>Why there is no high-water mark, ever.</b> PostgreSQL sequences commit out of order — one transaction
/// can take 100 and commit after another took 101 and committed — so "processed up to N" drops a row
/// silently. The claim filters <c>dispatched_at IS NULL</c>. Having no monotonic integer in the table at all
/// is what makes the wrong use unavailable rather than merely discouraged.
/// </para>
/// <para>
/// <b>Why <c>partition_key</c> exists with no reader yet.</b> Writing it from this first migration makes F7's
/// partitioned claim an additive change instead of a migration of a shipped table, and the column is named
/// after the <em>registered</em> CloudEvents <c>partitionkey</c> attribute — see
/// <see cref="AlvoEvent.PartitionKey"/> — so the column and the attribute cannot drift.
/// </para>
/// <para>
/// <b>Why provenance is not duplicated into columns.</b> An <c>actor</c>, <c>correlation_id</c> and
/// <c>provenance_depth</c> column would be a second authority for values the envelope in <c>payload</c>
/// already carries, and two authorities for one value is how the two come to disagree. Only
/// <c>partition_key</c> is duplicated, and only because F7 must index it.
/// </para>
/// <para>
/// <b>Its bind-parameter names are not in <see cref="PolicyParameterPrefix"/>.</b> That registry exists
/// because one composed read statement carries fragments from several renderers that never see each other's
/// output; the statements here are hand-written, single-fragment, and touch no entity table, so there is no
/// second contributor a name could collide with — the same argument
/// <see cref="IdempotencyTable"/> already records.
/// </para>
/// </remarks>
internal static class OutboxTable
{
    /// <summary>The framework's outbox table for a prefix, e.g. <c>alvo_outbox</c>.</summary>
    /// <param name="schemaPrefix">The validated <see cref="AlvoOptions.SchemaPrefix"/>.</param>
    internal static string NameFor(string schemaPrefix) => $"{schemaPrefix}_outbox";

    /// <summary>
    /// The <c>CREATE TABLE IF NOT EXISTS</c> for <paramref name="tableName"/>, safe to run repeatedly.
    /// </summary>
    /// <param name="tableName">The table name, already prefixed by <see cref="NameFor"/>.</param>
    /// <remarks>
    /// <para>
    /// The name is a validated identifier assembled from <see cref="AlvoOptions.SchemaPrefix"/> (see
    /// <see cref="SystemSchemaInitializer"/>'s constructor guard), never caller-supplied data — and SQL has
    /// no bind-parameter form of an identifier, so interpolation is the only way to place it at all.
    /// </para>
    /// <para>
    /// <c>claimed_at</c>, <c>claimed_by</c> and <c>dispatched_at</c> are the only nullable columns, and their
    /// nullability is the queue's whole state machine: never-touched is <c>claimed_at IS NULL</c> and
    /// undelivered is <c>dispatched_at IS NULL</c>. Both read as SQL <c>NULL</c> semantics rather than as a
    /// sentinel value, which is what lets the claim be one portable statement.
    /// </para>
    /// <para>
    /// <b><c>claimed_by</c> is what distinguishes the two waiting states, so it is load-bearing rather than
    /// informational.</b> With it set, <c>claimed_at</c> is when the current claim <em>started</em> and the row
    /// is recoverable only once the lease has run out — the crash-recovery path. With it <see langword="null"/>
    /// and <c>claimed_at</c> set, the row was <em>released</em> and <c>claimed_at</c> is the instant it becomes
    /// claimable again — the retry backoff. One column, two meanings, and the holder's name is the discriminator
    /// rather than a second timestamp column no engine would need.
    /// </para>
    /// </remarks>
    internal static string Ddl(string tableName) =>
        $"""
        CREATE TABLE IF NOT EXISTS {tableName} (
            id TEXT NOT NULL PRIMARY KEY,
            event_type TEXT NOT NULL,
            partition_key TEXT NOT NULL,
            payload TEXT NOT NULL,
            created_at TEXT NOT NULL,
            claimed_at TEXT NULL,
            claimed_by TEXT NULL,
            attempts INTEGER NOT NULL,
            dispatched_at TEXT NULL
        )
        """;

    /// <summary>
    /// Creates the table if it does not exist yet, on <paramref name="connection"/> and outside any
    /// transaction.
    /// </summary>
    /// <param name="connection">An open connection; opened by the caller, never owned here.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="ct">A token to cancel the operation.</param>
    /// <remarks>
    /// <para>
    /// <b>Deliberately not inside the write transaction</b>, for the reason
    /// <see cref="IdempotencyTable.EnsureAsync"/> records from measurement: run there, this DDL serialises two
    /// concurrent creates, because PostgreSQL will not let two transactions create one table name at once — so
    /// the second blocks on the first instead of reaching the row-level control that is the actual guard.
    /// Outside a transaction it also commits on its own, which is what makes a caller's ensure-once memo
    /// honest: a memo set inside a transaction that later rolled back would claim a table exists that went
    /// back with everything else.
    /// </para>
    /// <para>
    /// Two connections racing the very first create may still collide here — a duplicate-relation error on
    /// PostgreSQL, because <c>CREATE TABLE IF NOT EXISTS</c> is not atomic there. On the apply path
    /// <see cref="SystemSchemaInitializer"/> already absorbs that by probing whether the table exists
    /// afterwards; on the write path it is a storage write failure like any other, retried by the caller,
    /// whose next attempt finds the table in place.
    /// </para>
    /// </remarks>
    internal static async Task EnsureAsync(DbConnection connection, string tableName, CancellationToken ct)
    {
        var command = connection.CreateCommand();
        await using (command.ConfigureAwait(false))
        {
            command.CommandText = Ddl(tableName);
            await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Appends <paramref name="event"/> to the outbox <b>on the caller's own transaction</b>, so the event and
    /// the row it describes commit together or not at all.
    /// </summary>
    /// <param name="connection">The write transaction's own connection.</param>
    /// <param name="transaction">The in-flight write transaction.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="event">The envelope to store.</param>
    /// <param name="ct">A token to cancel the operation.</param>
    /// <remarks>
    /// <para>
    /// <b>The transaction is the whole seam.</b> Sequenced explicitly here rather than hung off
    /// <c>SaveChanges</c>: an interceptor never fires for <c>ExecuteUpdate</c> or <c>ExecuteDelete</c>, which
    /// is how this data path writes an update and a delete — the two operations that most need an event — so
    /// the idiomatic EF placement would silently emit on create only.
    /// </para>
    /// <para>
    /// <b>What actually makes the insert atomic with the write is the <em>connection</em>, and
    /// <c>command.Transaction</c> is the contract rather than the mechanism.</b> Measured while proving the
    /// write sites emit: deleting <c>command.Transaction = transaction</c> leaves every outbox fact green on
    /// both shipped engines, because a SQLite transaction and a PostgreSQL one both belong to the connection,
    /// so any statement on that connection is already inside it. The assignment stays because ADO.NET's own
    /// contract requires it — <c>SqlCommand</c> (the Azure SQL driver this family plans to add) throws when a
    /// connection has an open transaction the command does not name — and because the seam is a claim about
    /// which transaction the row rides, not a hope. The mutation that <em>is</em> caught is the one that moves
    /// the insert onto a connection of its own; that leaves an orphan event behind a rolled-back write, and
    /// <c>AlvoDataOutboxTests.Two_concurrent_idempotent_creates_on_one_key_emit_exactly_one_event</c> is the
    /// fact that sees it.
    /// </para>
    /// <para>
    /// <c>created_at</c> is rendered by <see cref="StoredInstant.Text"/> from the envelope's own
    /// <see cref="AlvoEvent.Time"/>, which is the write's audit instant and the instant
    /// <see cref="AlvoEventId.Create(DateTimeOffset)"/> embedded in the id — one instant, three places, rather
    /// than three clock reads.
    /// </para>
    /// <para>
    /// <c>claimed_at</c>, <c>claimed_by</c> and <c>dispatched_at</c> are left out of the column list rather
    /// than bound to <see langword="null"/>: the state machine's initial state is the absence of a claim and
    /// of a delivery, and a column list that names them would invite a sentinel.
    /// </para>
    /// </remarks>
    internal static async Task InsertAsync(
        DbConnection connection,
        DbTransaction transaction,
        string tableName,
        AlvoEvent @event,
        CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(@event);

        var command = connection.CreateCommand();
        await using (command.ConfigureAwait(false))
        {
            command.Transaction = transaction;
            command.CommandText =
                $"""
                INSERT INTO {tableName} (id, event_type, partition_key, payload, created_at, attempts)
                VALUES (@id, @event_type, @partition_key, @payload, @created_at, @attempts)
                """;
            RelationalSqlBatch.AddParameter(command, "@id", @event.Id.ToString());
            RelationalSqlBatch.AddParameter(command, "@event_type", @event.Type);
            RelationalSqlBatch.AddParameter(command, "@partition_key", @event.PartitionKey);
            RelationalSqlBatch.AddParameter(command, "@payload", AlvoEventJson.Write(@event));
            RelationalSqlBatch.AddParameter(command, "@created_at", StoredInstant.Text(@event.Time));
            RelationalSqlBatch.AddParameter(command, "@attempts", UndeliveredAttempts);

            await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// The claim: takes the oldest claimable entries of <paramref name="tableName"/>, stamps them, counts the
    /// attempt, and returns them.
    /// </summary>
    /// <param name="tableName">The table name, already prefixed by <see cref="NameFor"/>.</param>
    /// <remarks>
    /// <para>
    /// <b>The outer <c>WHERE</c> repeats the subquery's claimability predicate, and that is the whole
    /// correctness of the statement — not a belt on a brace.</b> Measured without it (spike Q4): <em>"A claimed
    /// 10, B claimed 10, overlap 10 (must be 0); rows with attempts &gt; 1: 10"</em> — two claimants deliver
    /// <b>every</b> entry twice. Under <c>READ COMMITTED</c>, PostgreSQL's EvalPlanQual re-check runs the
    /// <b>outer</b> <c>WHERE</c> again against the row the winner just updated, and nothing else; the
    /// subquery's <c>claimed_at IS NULL</c> was evaluated before the block and is never re-checked, so the
    /// loser's <c>id IN (…)</c> still holds and it re-claims what the winner took. With the predicate
    /// repeated: <em>"A claimed 10, B claimed 0, overlap 0; rows with attempts &gt; 1: 0"</em>. Anyone tempted
    /// to call it redundant is reading the subquery as if it re-ran.
    /// </para>
    /// <para>
    /// <b>Why raw SQL and not LINQ.</b> <c>UseRelationalNulls()</c> is on in both drivers, so a LINQ predicate
    /// over a nullable column would have to be written <c>x != null &amp;&amp; x &lt; y</c> against C#'s
    /// reading of the same text (<c>docs/architecture/data-path.md</c>). Raw SQL has SQL's semantics natively,
    /// so the constraint is met by construction rather than by whoever edits this next remembering it;
    /// <c>ChangeTrackerReachTests.The_outbox_claim_is_raw_sql_and_never_linq_over_the_context</c> holds the
    /// line.
    /// </para>
    /// <para>
    /// <b>Why the <c>ORDER BY</c> and the <c>LIMIT</c> are in the subquery.</b> Measured on <b>both</b> engines
    /// (Q3): the parser names <c>ORDER</c>, not <c>limit</c> — SQLite <c>'near "ORDER": syntax error'</c>,
    /// PostgreSQL <c>42601 syntax error at or near "ORDER"</c> — so this is portability rather than a SQLite
    /// workaround. The bundled <c>e_sqlite3</c> also reports <c>SQLITE_ENABLE_UPDATE_DELETE_LIMIT</c> unset.
    /// </para>
    /// <para>
    /// <b>Why the result is re-sorted in process.</b> <c>RETURNING</c>'s row order is arbitrary in measured
    /// fact on both engines — <c>RETURNING already sorted: False</c> for SQLite <em>and</em> PostgreSQL (Q3) —
    /// so the subquery's <c>ORDER BY</c> decides <em>which</em> entries are claimed, never in what order they
    /// come back. <see cref="EfCoreOutboxStore"/> sorts what it read.
    /// </para>
    /// <para>
    /// <b>Why the claimability predicate has three branches.</b> A never-touched row has
    /// <c>claimed_at IS NULL</c>. A <em>released</em> row has <c>claimed_by IS NULL</c> and <c>claimed_at</c>
    /// holding the instant it may be retried, so it is compared against <c>@now</c>. A <em>held</em> row has
    /// <c>claimed_by</c> set and <c>claimed_at</c> holding when the claim began, so it is compared against
    /// <c>@stale_before</c> — the lease. The released branch compares <em>inclusively</em>, because a release with
    /// no backoff stamps the present instant and the port promises it is claimable at once. Comparing a released row against the lease would make every failed
    /// delivery wait out a five-minute crash-recovery window; comparing a held row against <c>@now</c> would
    /// re-claim an entry that is still in flight, which is a duplicate delivery per tick.
    /// </para>
    /// <para>
    /// <b>Why there is no <c>SKIP LOCKED</c>.</b> It skips the <b>row</b>, not the <b>key</b>, so it delivers
    /// neither global nor per-entity-key ordering; with exactly one dispatcher it buys nothing, and a new
    /// <see cref="IAlvoSqlDialect"/> member would be a public-API change in a driver package for a seam F7 will
    /// design properly. Q4 measured that a second claimant blocks and then claims <b>nothing</b> — with this
    /// statement, and every entry twice without its outer predicate.
    /// </para>
    /// </remarks>
    internal static string ClaimSql(string tableName) =>
        $"""
        UPDATE {tableName} SET claimed_at = @claimed_at, claimed_by = @claimed_by,
                               attempts = attempts + 1
         WHERE dispatched_at IS NULL
           AND {WithinAttemptCeiling}
           AND {Claimable}
           AND id IN (SELECT id FROM {tableName}
                       WHERE dispatched_at IS NULL
                         AND {WithinAttemptCeiling}
                         AND {Claimable}
                       ORDER BY id
                       LIMIT @batch)
        RETURNING id, event_type, partition_key, payload, attempts
        """;

    /// <summary>When an entry still has attempts left: it has not reached the ceiling.</summary>
    /// <remarks>
    /// <b>A constant in both halves for the same reason <see cref="Claimable"/> is one, and it was in the
    /// subquery alone.</b> The EvalPlanQual argument the remarks on <see cref="ClaimSql"/> make about
    /// claimability applies verbatim to the ceiling: the re-check runs the <em>outer</em> <c>WHERE</c> against
    /// the newer row version and never re-runs the subquery. So a claimant whose subquery snapshot saw an entry
    /// at <c>attempts = @max_attempts - 1</c> could be woken after another claimant had claimed, failed and
    /// released it — leaving it genuinely claimable, genuinely at the ceiling — and the outer predicate had
    /// nothing to refuse it with.
    /// <para>
    /// <b>What that cost, stated so the severity is not inflated on a later read.</b> The overshoot is bounded
    /// by the number of racing claimants, because a claimant only reaches the row at all if its own subquery
    /// saw room; an entry pushed to <c>@max_attempts + 1</c> is then <em>more</em> excluded, not less, since the
    /// subquery still gates on this predicate. So no entry was delivered twice and none was lost — what broke
    /// is only the ceiling's own promise in <see cref="MMLib.Alvo.Events.IOutboxStore.ClaimAsync"/>, that an
    /// entry stops being claimed once it is past the bound.
    /// </para>
    /// </remarks>
    private const string WithinAttemptCeiling = "attempts < @max_attempts";

    /// <summary>
    /// When an undelivered row may be taken: never claimed at all, released and past its backoff, or held on a
    /// lease that has run out.
    /// </summary>
    /// <remarks>
    /// One constant used in both halves of <see cref="ClaimSql"/>, because the outer <c>WHERE</c> repeating the
    /// subquery's predicate is the statement's whole correctness (see the remarks above) and two spellings of it
    /// is how the outer copy comes to be the weaker one.
    /// </remarks>
    private const string Claimable =
        """
        (claimed_at IS NULL
                 OR (claimed_by IS NULL AND claimed_at <= @now)
                 OR (claimed_by IS NOT NULL AND claimed_at < @stale_before))
        """;

    /// <summary>Retires one entry of <paramref name="tableName"/>: it was delivered.</summary>
    /// <param name="tableName">The table name, already prefixed by <see cref="NameFor"/>.</param>
    /// <remarks>
    /// The claim reads <c>dispatched_at IS NULL</c>, so stamping it is what makes delivery final — it outlives
    /// the lease, which <c>claimed_at</c> alone would not. <c>claimed_at</c> and <c>claimed_by</c> are left in
    /// place, because they are the only record of who delivered the entry.
    /// </remarks>
    internal static string MarkDispatchedSql(string tableName) =>
        $"UPDATE {tableName} SET dispatched_at = @dispatched_at WHERE id = @id";

    /// <summary>
    /// Hands one entry of <paramref name="tableName"/> back, claimable again once the stamped instant passes.
    /// </summary>
    /// <param name="tableName">The table name, already prefixed by <see cref="NameFor"/>.</param>
    /// <remarks>
    /// <para>
    /// <c>attempts</c> is deliberately untouched: releasing is how a dispatcher says it could not deliver, and
    /// resetting the count would make the attempt ceiling unreachable and retry a poison event forever.
    /// </para>
    /// <para>
    /// <b><c>claimed_by</c> is cleared and <c>claimed_at</c> is stamped forward, and the pairing is the
    /// backoff.</b> Clearing the holder is what moves the row into the released state <see cref="ClaimSql"/>
    /// compares against <c>@now</c> rather than against the lease; <c>claimed_at</c> then carries when it may be
    /// retried. Setting <c>claimed_at = NULL</c> instead — the obvious spelling — makes the row claimable on the
    /// dispatcher's very next iteration, and the idle wait runs only after an <em>empty</em> claim, so one
    /// restarting receiver spends the whole attempt ceiling in milliseconds.
    /// </para>
    /// </remarks>
    internal static string ReleaseSql(string tableName) =>
        $"UPDATE {tableName} SET claimed_at = @claimed_at, claimed_by = NULL WHERE id = @id";

    /// <summary>How many delivery attempts a freshly written event has had.</summary>
    private const int UndeliveredAttempts = 0;
}
