using MMLib.Alvo.Events;

using System.Data.Common;

namespace MMLib.Alvo.Data.EntityFrameworkCore.Internal;

/// <summary>
/// Alvo's own transactional outbox: its name, the DDL that creates it, and the insert the write path adds to
/// the transaction that is already committing the row. A framework bookkeeping table like the
/// descriptor-versions and idempotency-record ones, not something the descriptor-diff engine produces.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why <c>id</c> is the ordering key and there is no <c>sequence</c> column.</b> A UUIDv7 is time-ordered
/// in its high 48 bits and its stored text sorts lexicographically in time order on both shipped engines, so
/// the primary key <em>is</em> the queue order — with DDL identical on SQLite and PostgreSQL, honouring
/// <see cref="SystemSchemaInitializer"/>'s stated invariant. An <c>AUTOINCREMENT</c>/<c>IDENTITY</c> column
/// would break that invariant with no precedent in this repository, because each engine refuses the other's
/// spelling: SQLite refuses <c>… GENERATED BY DEFAULT AS IDENTITY</c> and PostgreSQL refuses
/// <c>AUTOINCREMENT</c>. Two consequences of the same measurement belong here, because neither is visible
/// from the DDL: the id is minted by <see cref="AlvoEventId.Create(DateTimeOffset)"/> and never by
/// <c>Guid.CreateVersion7()</c>, which sorts 49.9 % of its same-millisecond pairs backwards; and the column
/// is <c>TEXT</c> rather than a <c>BLOB</c>, because <see cref="Guid"/>'s default byte order is not
/// time-sortable at all. Measured in
/// <c>docs/superpowers/specs/evidence/2026-08-03-f3-pr5a-events/spike.txt</c>, Q1, Q2, Q6 and Q7 — Q7 is what
/// disqualifies <c>created_at</c> as the alternative: 10 000 successive clock reads produce 3 distinct values
/// at millisecond precision, and the audit stamp binds one instant per write, so ties there are structural.
/// </para>
/// <para>
/// <b>Why <c>SERIAL</c> is refused even though SQLite does not reject it.</b> SQLite <em>accepts</em>
/// <c>seq SERIAL</c>, parsing <c>SERIAL</c> as an unrecognised column type and silently giving a nullable
/// column that never increments (Q6). A "portable <c>SERIAL</c>" therefore passes every SQLite test in CI and
/// loses ordering in production, which is why <c>OutboxTableTests</c> asserts its absence rather than trusting
/// that nobody reaches for it.
/// </para>
/// <para>
/// <b>Why there is no high-water mark, ever.</b> PostgreSQL sequences commit out of order — one transaction
/// can take 100 and commit after another took 101 and committed — so "processed up to N" drops a row
/// silently. The claim filters <c>dispatched_at IS NULL</c>. Having no monotonic integer in the table at all
/// is what makes the wrong use unavailable rather than merely discouraged.
/// </para>
/// <para>
/// <b>Why <c>partition_key</c> exists with no reader yet.</b> Writing it from this first migration makes F7's
/// partitioned claim an additive change instead of a migration of a shipped table, and the column is named
/// after the <em>registered</em> CloudEvents <c>partitionkey</c> attribute — see
/// <see cref="AlvoEvent.PartitionKey"/> — so the column and the attribute cannot drift.
/// </para>
/// <para>
/// <b>Why provenance is not duplicated into columns.</b> An <c>actor</c>, <c>correlation_id</c> and
/// <c>provenance_depth</c> column would be a second authority for values the envelope in <c>payload</c>
/// already carries, and two authorities for one value is how the two come to disagree. Only
/// <c>partition_key</c> is duplicated, and only because F7 must index it.
/// </para>
/// <para>
/// <b>Its bind-parameter names are not in <see cref="PolicyParameterPrefix"/>.</b> That registry exists
/// because one composed read statement carries fragments from several renderers that never see each other's
/// output; the statements here are hand-written, single-fragment, and touch no entity table, so there is no
/// second contributor a name could collide with — the same argument
/// <see cref="IdempotencyTable"/> already records.
/// </para>
/// </remarks>
internal static class OutboxTable
{
    /// <summary>The framework's outbox table for a prefix, e.g. <c>alvo_outbox</c>.</summary>
    /// <param name="schemaPrefix">The validated <see cref="AlvoOptions.SchemaPrefix"/>.</param>
    internal static string NameFor(string schemaPrefix) => $"{schemaPrefix}_outbox";

    /// <summary>
    /// The <c>CREATE TABLE IF NOT EXISTS</c> for <paramref name="tableName"/>, safe to run repeatedly.
    /// </summary>
    /// <param name="tableName">The table name, already prefixed by <see cref="NameFor"/>.</param>
    /// <remarks>
    /// <para>
    /// The name is a validated identifier assembled from <see cref="AlvoOptions.SchemaPrefix"/> (see
    /// <see cref="SystemSchemaInitializer"/>'s constructor guard), never caller-supplied data — and SQL has
    /// no bind-parameter form of an identifier, so interpolation is the only way to place it at all.
    /// </para>
    /// <para>
    /// <c>claimed_at</c>, <c>claimed_by</c> and <c>dispatched_at</c> are the only nullable columns, and their
    /// nullability is the queue's whole state machine: unclaimed is <c>claimed_at IS NULL</c> and undelivered
    /// is <c>dispatched_at IS NULL</c>. Both read as SQL <c>NULL</c> semantics rather than as a sentinel
    /// value, which is what lets the claim be one portable statement.
    /// </para>
    /// </remarks>
    internal static string Ddl(string tableName) =>
        $"""
        CREATE TABLE IF NOT EXISTS {tableName} (
            id TEXT NOT NULL PRIMARY KEY,
            event_type TEXT NOT NULL,
            partition_key TEXT NOT NULL,
            payload TEXT NOT NULL,
            created_at TEXT NOT NULL,
            claimed_at TEXT NULL,
            claimed_by TEXT NULL,
            attempts INTEGER NOT NULL,
            dispatched_at TEXT NULL
        )
        """;

    /// <summary>
    /// Creates the table if it does not exist yet, on <paramref name="connection"/> and outside any
    /// transaction.
    /// </summary>
    /// <param name="connection">An open connection; opened by the caller, never owned here.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="ct">A token to cancel the operation.</param>
    /// <remarks>
    /// <para>
    /// <b>Deliberately not inside the write transaction</b>, for the reason
    /// <see cref="IdempotencyTable.EnsureAsync"/> records from measurement: run there, this DDL serialises two
    /// concurrent creates, because PostgreSQL will not let two transactions create one table name at once — so
    /// the second blocks on the first instead of reaching the row-level control that is the actual guard.
    /// Outside a transaction it also commits on its own, which is what makes a caller's ensure-once memo
    /// honest: a memo set inside a transaction that later rolled back would claim a table exists that went
    /// back with everything else.
    /// </para>
    /// <para>
    /// Two connections racing the very first create may still collide here — a duplicate-relation error on
    /// PostgreSQL, because <c>CREATE TABLE IF NOT EXISTS</c> is not atomic there. On the apply path
    /// <see cref="SystemSchemaInitializer"/> already absorbs that by probing whether the table exists
    /// afterwards; on the write path it is a storage write failure like any other, retried by the caller,
    /// whose next attempt finds the table in place.
    /// </para>
    /// </remarks>
    internal static async Task EnsureAsync(DbConnection connection, string tableName, CancellationToken ct)
    {
        var command = connection.CreateCommand();
        await using (command.ConfigureAwait(false))
        {
            command.CommandText = Ddl(tableName);
            await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Appends <paramref name="event"/> to the outbox <b>on the caller's own transaction</b>, so the event and
    /// the row it describes commit together or not at all.
    /// </summary>
    /// <param name="connection">The write transaction's own connection.</param>
    /// <param name="transaction">The in-flight write transaction.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="event">The envelope to store.</param>
    /// <param name="ct">A token to cancel the operation.</param>
    /// <remarks>
    /// <para>
    /// <b>The transaction is the whole seam.</b> Sequenced explicitly here rather than hung off
    /// <c>SaveChanges</c>: an interceptor never fires for <c>ExecuteUpdate</c> or <c>ExecuteDelete</c>, which
    /// is how this data path writes an update and a delete — the two operations that most need an event — so
    /// the idiomatic EF placement would silently emit on create only.
    /// </para>
    /// <para>
    /// <c>created_at</c> is rendered by <see cref="StoredInstant.Text"/> from the envelope's own
    /// <see cref="AlvoEvent.Time"/>, which is the write's audit instant and the instant
    /// <see cref="AlvoEventId.Create(DateTimeOffset)"/> embedded in the id — one instant, three places, rather
    /// than three clock reads.
    /// </para>
    /// <para>
    /// <c>claimed_at</c>, <c>claimed_by</c> and <c>dispatched_at</c> are left out of the column list rather
    /// than bound to <see langword="null"/>: the state machine's initial state is the absence of a claim and
    /// of a delivery, and a column list that names them would invite a sentinel.
    /// </para>
    /// </remarks>
    internal static async Task InsertAsync(
        DbConnection connection,
        DbTransaction transaction,
        string tableName,
        AlvoEvent @event,
        CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(@event);

        var command = connection.CreateCommand();
        await using (command.ConfigureAwait(false))
        {
            command.Transaction = transaction;
            command.CommandText =
                $"""
                INSERT INTO {tableName} (id, event_type, partition_key, payload, created_at, attempts)
                VALUES (@id, @event_type, @partition_key, @payload, @created_at, @attempts)
                """;
            RelationalSqlBatch.AddParameter(command, "@id", @event.Id.ToString());
            RelationalSqlBatch.AddParameter(command, "@event_type", @event.Type);
            RelationalSqlBatch.AddParameter(command, "@partition_key", @event.PartitionKey);
            RelationalSqlBatch.AddParameter(command, "@payload", AlvoEventJson.Write(@event));
            RelationalSqlBatch.AddParameter(command, "@created_at", StoredInstant.Text(@event.Time));
            RelationalSqlBatch.AddParameter(command, "@attempts", UndeliveredAttempts);

            await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>How many delivery attempts a freshly written event has had.</summary>
    private const int UndeliveredAttempts = 0;
}
