using System.Globalization;
using System.Text.Json;

namespace MMLib.Alvo.Descriptor.Internal;

/// <summary>
/// Resolves a field's declared <c>default</c> into the literal the applied schema carries, and refuses
/// every declaration this build cannot honour.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why the refusals are here rather than at the database.</b> A literal a column cannot hold becomes a
/// <c>DEFAULT</c> clause the engine rejects while migrating, which reaches an operator as provider SQL in a
/// stack trace. Refused here it is a sentence naming their field and their value, before anything runs.
/// </para>
/// <para>
/// <b>The CEL half stays refused</b> (#113): <c>{"$cel": "now()"}</c> needs the caller's context at write
/// time, which is the <c>computed</c> machinery rather than a column default.
/// </para>
/// </remarks>
internal static class FieldDefault
{
    /// <summary>
    /// The literal this field defaults to, or <see langword="null"/> when it declares none.
    /// </summary>
    /// <param name="entity">The entity the field belongs to, for the message.</param>
    /// <param name="name">The field's name.</param>
    /// <param name="field">The declared field.</param>
    /// <returns>The literal, cloned so it outlives the parsed document.</returns>
    /// <exception cref="InvalidDataException">The declaration is one this build refuses.</exception>
    internal static JsonElement? Resolve(string entity, string name, FieldDescriptor field)
    {
        if (field.Default is not { } declared)
        {
            return null;
        }

        /* The '$cel' half is refused by UnhonouredFeatures' own walk, which runs before this and reads the
           one table both refusal passes read — a second refusal here would be a second wording of it. */
        if (declared.IsExpression)
        {
            return null;
        }

        RefuseOnAMaintainedField(entity, name, field);

        var literal = declared.Literal!.Value;

        /* A null is not a default. The JSON pass reads it as no declaration at all (an absent, empty or
           false value declares nothing), so refusing it here would be the two passes disagreeing about a
           descriptor that used to apply. */
        if (literal.ValueKind is JsonValueKind.Null)
        {
            return null;
        }

        RefuseLiteralTheFieldCannotHold(entity, name, field, literal);
        RefuseLiteralTheFacetsExclude(entity, name, field, literal);

        return literal.Clone();
    }

    /// <summary>
    /// Refuses a default on a field whose value is maintained for it.
    /// </summary>
    /// <remarks>
    /// <c>computed</c> is generated by the database from other columns and <c>rollup</c> is recomputed by the
    /// framework from a child entity's rows; neither can ever fall back to a default, so whichever of the two
    /// declarations won, the other would be a lie about a stored value. The frozen schema forbids the pair for
    /// both in the same way, and refusing only one of them would be a defence with a hole in it.
    /// </remarks>
    private static void RefuseOnAMaintainedField(string entity, string name, FieldDescriptor field)
    {
        var maintainer = field.Computed is not null ? "computed" : field.Rollup is not null ? "rollup" : null;
        if (maintainer is null)
        {
            return;
        }

        throw new InvalidDataException(
            $"Field '{entity}.{name}' declares both '{maintainer}' and 'default'. A {maintainer} field's value "
            + "is maintained for it, so it can never fall back to a default — whichever of the two won, the "
            + "other would be a lie about a stored value. Remove one.");
    }

    private static void RefuseLiteralTheFieldCannotHold(
        string entity, string name, FieldDescriptor field, JsonElement literal)
    {
        if (Fits(field, literal))
        {
            return;
        }

        throw new InvalidDataException(
            $"Field '{entity}.{name}' is of type '{field.Type}' and its 'default' is "
            + $"{literal.ValueKind.ToString().ToLowerInvariant()} — a value that column cannot hold. Declare a "
            + "default of the field's own type, or remove it and send the value on create.");
    }

    /// <summary>
    /// Refuses a literal of the right JSON kind that the field's own facets still exclude.
    /// </summary>
    /// <remarks>
    /// The facets are the column's own narrowing, so a default outside them is a value the API would refuse
    /// from a caller and the engine may refuse from the DDL. An over-length string reaches
    /// <c>varchar(n)</c> and fails as provider SQL while migrating; a value outside an enum's <c>values</c>
    /// is stored happily, because the enum is not a database constraint, and then read back as a value the
    /// record validator rejects. Both are refused here, where the message can name the field.
    /// </remarks>
    private static void RefuseLiteralTheFacetsExclude(
        string entity, string name, FieldDescriptor field, JsonElement literal)
    {
        if (Excluded(field, literal) is not { } reason)
        {
            return;
        }

        throw new InvalidDataException(
            $"Field '{entity}.{name}' declares a 'default' its own facets exclude: {reason}. Declare a default "
            + "the field would accept from a caller, or remove it.");
    }

    /// <summary>Why the field's facets exclude this literal, or <see langword="null"/> when they do not.</summary>
    private static string? Excluded(FieldDescriptor field, JsonElement literal)
    {
        if (literal.ValueKind is JsonValueKind.Number)
        {
            return OutsideDecimalBounds(field, literal);
        }

        if (literal.ValueKind is not JsonValueKind.String)
        {
            return null;
        }

        var value = literal.GetString() ?? string.Empty;

        return field switch
        {
            { MaxLength: { } max } when value.Length > max
                => $"it is {value.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)} characters "
                    + $"and 'maxLength' is {max.ToString(System.Globalization.CultureInfo.InvariantCulture)}",
            { Type: FieldType.Enum, Values: { Count: > 0 } values } when !values.Contains(value, StringComparer.Ordinal)
                => $"'{value}' is not one of the declared 'values'",
            { Type: FieldType.Uuid } when !Guid.TryParse(value, out _) => $"'{value}' is not a uuid",
            { Type: FieldType.Date or FieldType.DateTime } when !DateTimeOffset.TryParse(
                value, System.Globalization.CultureInfo.InvariantCulture, out _) => $"'{value}' is not a date",
            _ => null,
        };
    }

    /// <summary>
    /// Why a numeric default does not fit the column's declared precision, or <see langword="null"/>.
    /// </summary>
    /// <remarks>
    /// Left to apply, <c>12345.678</c> on a <c>decimal(5,2)</c> becomes a <c>DEFAULT</c> the engine rejects
    /// while migrating, and the write path then fills the out-of-range value into every create — the record
    /// validator's own bounds check only runs on values a caller supplied.
    /// </remarks>
    private static string? OutsideDecimalBounds(FieldDescriptor field, JsonElement literal)
    {
        if (field.Precision is not { } precision || !literal.TryGetDecimal(out var value))
        {
            return null;
        }

        var scale = field.Scale ?? 0;
        var digits = Math.Abs(value).ToString(
            "0.############################", CultureInfo.InvariantCulture);
        var parts = digits.Split('.');
        var integral = parts[0] == "0" ? 0 : parts[0].Length;
        var fractional = parts.Length > 1 ? parts[1].Length : 0;

        return fractional > scale || integral + scale > precision
            ? $"it does not fit 'precision' {precision.ToString(CultureInfo.InvariantCulture)} and 'scale' "
                + scale.ToString(CultureInfo.InvariantCulture)
            : null;
    }

    /// <summary>
    /// Whether the literal is one the field's type admits.
    /// </summary>
    /// <remarks>
    /// <b>The JSON kind, not a CLR conversion.</b> The question at apply is whether the descriptor is
    /// coherent, and a string <c>"1"</c> for an integer is incoherent however well it would parse — an author
    /// who meant a number wrote a string, and honouring it would teach them the schema is loose about types.
    /// A JSON number for a <c>decimal</c> is accepted whether or not it has a fractional part, because
    /// <c>2</c> and <c>2.0</c> are the same number.
    /// </remarks>
    private static bool Fits(FieldDescriptor field, JsonElement literal) => field.Type switch
    {
        FieldType.Boolean => literal.ValueKind is JsonValueKind.True or JsonValueKind.False,
        FieldType.Integer => literal.ValueKind is JsonValueKind.Number && literal.TryGetInt64(out _),
        FieldType.Decimal => literal.ValueKind is JsonValueKind.Number,
        FieldType.String or FieldType.Text or FieldType.Uuid
            or FieldType.Date or FieldType.DateTime or FieldType.Enum => literal.ValueKind is JsonValueKind.String,
        FieldType.Json => true,
        _ => false,
    };
}
