using System.Globalization;
using System.Text.Json;

namespace MMLib.Alvo.Descriptor.Internal;

/// <summary>
/// Resolves a field's declared <c>default</c> into the literal the applied schema carries, and refuses
/// every declaration this build cannot honour.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why the refusals are here rather than at the database.</b> A literal a column cannot hold becomes a
/// <c>DEFAULT</c> clause the engine rejects while migrating, which reaches an operator as provider SQL in a
/// stack trace. Refused here it is a sentence naming their field and their value, before anything runs.
/// </para>
/// <para>
/// <b>The CEL half stays refused</b> (#113): <c>{"$cel": "now()"}</c> needs the caller's context at write
/// time, which is the <c>computed</c> machinery rather than a column default.
/// </para>
/// </remarks>
internal static class FieldDefault
{
    /// <summary>
    /// The literal this field defaults to, or <see langword="null"/> when it declares none.
    /// </summary>
    /// <param name="entity">The entity the field belongs to, for the message.</param>
    /// <param name="name">The field's name.</param>
    /// <param name="field">The declared field.</param>
    /// <returns>The literal, cloned so it outlives the parsed document.</returns>
    /// <exception cref="InvalidDataException">The declaration is one this build refuses.</exception>
    internal static JsonElement? Resolve(string entity, string name, FieldDescriptor field)
    {
        if (field.Default is not { } declared)
        {
            return null;
        }

        /* The '$cel' half is refused by UnhonouredFeatures' own walk, which runs before this and reads the
           one table both refusal passes read — a second refusal here would be a second wording of it. */
        if (declared.IsExpression)
        {
            return null;
        }

        if (RefusalFor(field) is { } refusal)
        {
            throw new InvalidDataException($"Field '{entity}.{name}' {refusal}");
        }

        var literal = declared.Literal!.Value;

        /* A null is not a default. The JSON pass reads it as no declaration at all (an absent, empty or
           false value declares nothing), so refusing it here would be the two passes disagreeing about a
           descriptor that used to apply. */
        return literal.ValueKind is JsonValueKind.Null ? null : literal.Clone();
    }

    /// <summary>
    /// Why this build refuses the field's declared default, as one sentence continuing
    /// <c>"Field 'entity.name' …"</c>, or <see langword="null"/> when it accepts it.
    /// </summary>
    /// <remarks>
    /// <b>A returned reason rather than a throw, because two passes ask.</b> The mapper turns it into the
    /// <see cref="InvalidDataException"/> an apply raises; <c>DescriptorValidator</c> turns the same reason
    /// into a structured error carrying the field's JSON Pointer — which is what an agent reads (§0
    /// principle 4). Written as a throw only, a descriptor with a bad literal validated <em>clean</em> and
    /// then failed at apply with an untyped exception, which is the two passes disagreeing in the one
    /// direction that costs an author a debugging session.
    /// </remarks>
    /// <param name="field">The declared field.</param>
    internal static string? RefusalFor(FieldDescriptor field)
    {
        ArgumentNullException.ThrowIfNull(field);

        if (field.Default is not { } declared || declared.IsExpression)
        {
            return null;
        }

        var literal = declared.Literal!.Value;
        if (literal.ValueKind is JsonValueKind.Null)
        {
            return null;
        }

        return MaintainedElsewhere(field) ?? TypeCannotHold(field, literal) ?? FacetsExclude(field, literal);
    }

    /// <summary>
    /// Why a field whose value is maintained for it cannot also fall back to a default.
    /// </summary>
    /// <remarks>
    /// <c>computed</c> is generated by the database from other columns and <c>rollup</c> is recomputed by the
    /// framework from a child entity's rows. The frozen schema forbids the pair for both in the same way, and
    /// refusing only one of them would be a defence with a hole in it.
    /// </remarks>
    private static string? MaintainedElsewhere(FieldDescriptor field)
    {
        var maintainer = field.Computed is not null ? "computed" : field.Rollup is not null ? "rollup" : null;

        return maintainer is null
            ? null
            : $"declares both '{maintainer}' and 'default'. A {maintainer} field's value is maintained for it, "
                + "so it can never fall back to a default — whichever of the two won, the other would be a lie "
                + "about a stored value. Remove one.";
    }

    /// <summary>Why the field's own type cannot hold this literal, or <see langword="null"/>.</summary>
    private static string? TypeCannotHold(FieldDescriptor field, JsonElement literal) =>
        Fits(field, literal)
            ? null
            : $"is of type '{field.Type}' and its 'default' is {literal.ValueKind.ToString().ToLowerInvariant()}"
                + " — a value that column cannot hold. Declare a default of the field's own type, or remove it "
                + "and send the value on create.";

    /// <summary>Why the field's own facets exclude this literal, or <see langword="null"/>.</summary>
    private static string? FacetsExclude(FieldDescriptor field, JsonElement literal) =>
        Excluded(field, literal) is { } reason
            ? $"declares a 'default' its own facets exclude: {reason}. Declare a default the field would "
                + "accept from a caller, or remove it."
            : null;

    /// <summary>Why the field's facets exclude this literal, or <see langword="null"/> when they do not.</summary>
    private static string? Excluded(FieldDescriptor field, JsonElement literal)
    {
        if (literal.ValueKind is JsonValueKind.Number)
        {
            return OutsideDecimalBounds(field, literal);
        }

        if (literal.ValueKind is not JsonValueKind.String)
        {
            return null;
        }

        var value = literal.GetString() ?? string.Empty;

        return field switch
        {
            { MaxLength: { } max } when value.Length > max
                => $"it is {value.Length.ToString(System.Globalization.CultureInfo.InvariantCulture)} characters "
                    + $"and 'maxLength' is {max.ToString(System.Globalization.CultureInfo.InvariantCulture)}",
            { Type: FieldType.Enum, Values: { Count: > 0 } values } when !values.Contains(value, StringComparer.Ordinal)
                => $"'{value}' is not one of the declared 'values'",
            { Type: FieldType.Uuid } when !Guid.TryParse(value, out _) => $"'{value}' is not a uuid",
            { Type: FieldType.Date or FieldType.DateTime } when !DateTimeOffset.TryParse(
                value, System.Globalization.CultureInfo.InvariantCulture, out _) => $"'{value}' is not a date",
            _ => null,
        };
    }

    /// <summary>
    /// Why a numeric default does not fit the column's declared precision, or <see langword="null"/>.
    /// </summary>
    /// <remarks>
    /// Left to apply, <c>12345.678</c> on a <c>decimal(5,2)</c> becomes a <c>DEFAULT</c> the engine rejects
    /// while migrating, and the write path then fills the out-of-range value into every create — the record
    /// validator's own bounds check only runs on values a caller supplied.
    /// </remarks>
    private static string? OutsideDecimalBounds(FieldDescriptor field, JsonElement literal)
    {
        if (field.Precision is not { } precision || !literal.TryGetDecimal(out var value))
        {
            return null;
        }

        var scale = field.Scale ?? 0;
        var digits = Math.Abs(value).ToString(
            "0.############################", CultureInfo.InvariantCulture);
        var parts = digits.Split('.');
        var integral = parts[0] == "0" ? 0 : parts[0].Length;
        var fractional = parts.Length > 1 ? parts[1].Length : 0;

        return fractional > scale || integral + scale > precision
            ? $"it does not fit 'precision' {precision.ToString(CultureInfo.InvariantCulture)} and 'scale' "
                + scale.ToString(CultureInfo.InvariantCulture)
            : null;
    }

    /// <summary>
    /// Whether the literal is one the field's type admits.
    /// </summary>
    /// <remarks>
    /// <b>The JSON kind, not a CLR conversion.</b> The question at apply is whether the descriptor is
    /// coherent, and a string <c>"1"</c> for an integer is incoherent however well it would parse — an author
    /// who meant a number wrote a string, and honouring it would teach them the schema is loose about types.
    /// A JSON number for a <c>decimal</c> is accepted whether or not it has a fractional part, because
    /// <c>2</c> and <c>2.0</c> are the same number.
    /// </remarks>
    private static bool Fits(FieldDescriptor field, JsonElement literal) => field.Type switch
    {
        FieldType.Boolean => literal.ValueKind is JsonValueKind.True or JsonValueKind.False,
        FieldType.Integer => literal.ValueKind is JsonValueKind.Number && literal.TryGetInt64(out _),
        FieldType.Decimal => literal.ValueKind is JsonValueKind.Number,
        FieldType.String or FieldType.Text or FieldType.Uuid
            or FieldType.Date or FieldType.DateTime or FieldType.Enum => literal.ValueKind is JsonValueKind.String,
        FieldType.Json => true,
        _ => false,
    };
}
