import { readFile, writeFile } from 'node:fs/promises';

const source = new URL('../../src/MMLib.Alvo.Admin/wwwroot/alvo.css', import.meta.url);
const target = new URL('../src/styles/alvo-tokens.generated.css', import.meta.url);
const opener = '@layer tokens {';

const css = await readFile(source, 'utf8');
const start = css.indexOf(opener);
if (start < 0) throw new Error(`sync-tokens: no "${opener}" block in ${source.pathname}`);
const bodyStart = start + opener.length;
const end = closingBrace(css, bodyStart);
const header = '/* Generated by website/scripts/sync-tokens.mjs from src/MMLib.Alvo.Admin/wwwroot/alvo.css. Do not edit. */\n';
await writeFile(target, `${header}@layer alvo-tokens {${css.slice(bodyStart, end)}}\n`);

function closingBrace(text, from) {
  let depth = 1;
  for (let i = from; i < text.length; i++) {
    if (text.startsWith('/*', i)) { i = text.indexOf('*/', i + 2) + 1; continue; }
    if (text[i] === '{') depth++;
    else if (text[i] === '}' && --depth === 0) return i;
  }
  throw new Error('sync-tokens: the tokens block is not closed');
}
