using Microsoft.Data.Sqlite;
using MMLib.Alvo.Data.EntityFrameworkCore;
using MMLib.Alvo.Schema;
using System.Data.Common;

namespace MMLib.Alvo.Data.Sqlite;

/// <summary>
/// SQLite's <see cref="IAlvoSqlDialect"/>: unqualified quoted tables, a standard <c>CAST</c> around the
/// store type EF resolved, and no row lock — SQLite serializes write transactions instead.
/// </summary>
public sealed class SqliteSqlDialect : IAlvoSqlDialect
{
    /// <inheritdoc/>
    /// <remarks>
    /// SQLite has no locking clause in either mode: a write transaction takes a database-wide lock, so a
    /// pre-image read and the write that follows it are already serialized against another writer. The
    /// answer is therefore the same for both mutations, and it is <see cref="string.Empty"/> rather than a
    /// clause the engine would reject.
    /// </remarks>
    public string RowLockClause(PreImageMutation mutation) => string.Empty;

    /// <inheritdoc/>
    /// <remarks>
    /// <paramref name="lockedPreImageFor"/> is ignored, and that is the honest answer rather than a missing
    /// one: SQLite expresses row locking in neither position — not as a trailing clause and not as a table
    /// hint — because a write transaction already takes a database-wide lock. A pre-image read therefore
    /// renders exactly the same table source as an ordinary one.
    /// </remarks>
    public string RenderTable(EntitySchema entity, PreImageMutation? lockedPreImageFor)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return AlvoSqlIdentifier.Quote(entity.Name);
    }

    /// <inheritdoc/>
    public string RenderColumn(string columnName) => AlvoSqlIdentifier.Quote(columnName);

    /// <inheritdoc/>
    public string RenderNullProjection(string storeType)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(storeType);
        return $"CAST(NULL AS {storeType})";
    }

    /// <summary><c>SQLITE_CONSTRAINT_UNIQUE</c> (2067): a <c>UNIQUE</c> index refused the row.</summary>
    private const int ConstraintUnique = 2067;

    /// <summary><c>SQLITE_CONSTRAINT_PRIMARYKEY</c> (1555): the same failure, on the primary key.</summary>
    private const int ConstraintPrimaryKey = 1555;

    /// <summary><c>SQLITE_CONSTRAINT_FOREIGNKEY</c> (787): what a <c>RESTRICT</c>-ed reference raises.</summary>
    private const int ConstraintForeignKey = 787;

    /// <summary>SQLite's own prefix on the one message that names columns.</summary>
    private const string UniqueFailurePrefix = "UNIQUE constraint failed: ";

    /// <inheritdoc/>
    /// <remarks>
    /// <para>
    /// Decided from the <b>extended result code</b> — the numeric code SQLite documents per constraint class —
    /// and never from the primary code 19 (<c>SQLITE_CONSTRAINT</c>) alone, which also covers <c>CHECK</c>,
    /// <c>NOT NULL</c> and trigger failures that are not a caller conflict.
    /// </para>
    /// <para>
    /// <b>Why the columns are read out of the message here, when the shared path may not.</b> SQLite exposes
    /// no constraint name at all — there is no such property on <c>SqliteException</c> and no index name in
    /// the error — so the only place the violated columns appear is the message
    /// (<c>UNIQUE constraint failed: work_orders.tenant_id, work_orders.reference</c>). That text is
    /// generated by SQLite itself, is not localized, and contains no caller-supplied value; reading it is
    /// therefore sound <em>in this driver</em>, which owns SQLite's spelling, and unsound in the shared data
    /// path, which would then depend on one engine's prose. That is the entire reason this member exists on
    /// the dialect. The parse is fail-soft: a message this cannot read yields no columns, the shared path
    /// finds no fields, and the failure keeps propagating as it did before.
    /// </para>
    /// <para>
    /// <c>SQLITE_CONSTRAINT_PRIMARYKEY</c> is decoded as <see cref="AlvoConstraintKind.Unique"/> rather than
    /// filtered out here: the columns it names are framework-managed, and dropping a conflict confined to
    /// those is the shared path's decision to make once, for every engine, rather than each driver's.
    /// </para>
    /// <para>
    /// A foreign-key failure names nothing at all — SQLite's message is the bare
    /// <c>FOREIGN KEY constraint failed</c> — which is the engine difference #139 asked to have measured
    /// rather than assumed. It costs nothing here, because the refusal names no entity on any engine.
    /// </para>
    /// </remarks>
    public SqlConstraintViolation? DecodeConstraintViolation(DbException failure)
    {
        ArgumentNullException.ThrowIfNull(failure);
        if (failure is not SqliteException sqlite)
        {
            return null;
        }

        return sqlite.SqliteExtendedErrorCode switch
        {
            ConstraintUnique or ConstraintPrimaryKey => new SqlConstraintViolation
            {
                Kind = AlvoConstraintKind.Unique,
                Columns = ViolatedColumns(sqlite.Message),
            },
            ConstraintForeignKey => new SqlConstraintViolation { Kind = AlvoConstraintKind.Referenced },
            _ => WithoutAnExtendedCode(sqlite),
        };
    }

    /// <summary>SQLITE_CONSTRAINT (19): some constraint refused the statement, without saying which.</summary>
    private const int Constraint = 19;

    /// <summary>SQLite's own prefix on a foreign-key failure, which names nothing else at all.</summary>
    private const string ForeignKeyFailurePrefix = "FOREIGN KEY constraint failed";

    /// <summary>
    /// The same decision from the primary code and the message, for the paths where the extended code does not
    /// survive — measured, not anticipated: <c>ExecuteDelete</c>'s foreign-key failure arrives as bare
    /// <c>SQLITE_CONSTRAINT</c> while <c>SaveChanges</c>' unique failure carries the extended code.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>Microsoft.Data.Sqlite</c> only reads <c>sqlite3_extended_errcode</c> when the connection handle still
    /// agrees with the return code it is about; otherwise it reports the primary code in both places. That is
    /// invisible from the exception, so relying on the extended code alone would have made the <c>409</c>
    /// depend on which EF statement happened to raise the failure — a 500 on a <c>restrict</c>-ed delete and a
    /// 409 on a duplicate, from the same engine.
    /// </para>
    /// <para>
    /// The narrowing is still the numeric code: only <see cref="Constraint"/> reaches here, so a message match
    /// can never promote an unrelated failure. Within that class the two prefixes are SQLite's own generated
    /// text, unlocalized and free of caller values — and anything else in the class (a <c>CHECK</c>, a
    /// <c>NOT NULL</c>, a trigger) still answers <see langword="null"/>.
    /// </para>
    /// </remarks>
    /// <param name="sqlite">The engine's exception.</param>
    private static SqlConstraintViolation? WithoutAnExtendedCode(SqliteException sqlite)
    {
        if (sqlite.SqliteErrorCode != Constraint)
        {
            return null;
        }

        if (sqlite.Message.Contains(ForeignKeyFailurePrefix, StringComparison.Ordinal))
        {
            return new SqlConstraintViolation { Kind = AlvoConstraintKind.Referenced };
        }

        return sqlite.Message.Contains(UniqueFailurePrefix, StringComparison.Ordinal)
            ? new SqlConstraintViolation
            {
                Kind = AlvoConstraintKind.Unique,
                Columns = ViolatedColumns(sqlite.Message),
            }
            : null;
    }

    /// <summary>
    /// The bare column names in a <c>UNIQUE constraint failed: t.a, t.b</c> message, or nothing when the
    /// message is not that shape.
    /// </summary>
    /// <remarks>
    /// Each entry is <c>table.column</c>, so the table qualifier is stripped here — the shared path resolves
    /// against the entity it is already writing and has no need to re-derive which table that was.
    /// </remarks>
    /// <param name="message">The exception's message.</param>
    private static IReadOnlyList<string> ViolatedColumns(string message)
    {
        var start = message.IndexOf(UniqueFailurePrefix, StringComparison.Ordinal);
        if (start < 0)
        {
            return [];
        }

        var list = message[(start + UniqueFailurePrefix.Length)..].TrimEnd('\'', '.', ' ');
        return [.. list.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(Unqualified)
            .Where(column => column.Length > 0)];
    }

    /// <summary>The column half of a <c>table.column</c> pair.</summary>
    /// <param name="qualified">The qualified column name.</param>
    private static string Unqualified(string qualified)
    {
        var dot = qualified.LastIndexOf('.');
        return dot < 0 ? qualified : qualified[(dot + 1)..];
    }
}
